baseURL = "https://yasinkaraaslan.com"
title = "Yasin Karaaslan"
copyright = '<a href="/tos" target="_blank">© 2023 - 2024 Yasin Karaaslan</a>'
#paginate = 10
enableRobotsTXT = true
pluralizeListTitles = false

# Enable to calculate the last modified date from Git history and show it in the post header
enableGitInfo = true

[build]
  noJSConfigInAssets = true
  [build.buildStats]
    # With each build, Hugo writes a hugo_stats.json file that contains arrays
    # of the class attributes, id attributes, and tags of each HTML element 
    # within the published site. For production builds, this file is required 
    # by PurgeCSS to prune unused CSS.
    enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This setting allows inlining <script> and <style> tags in markdown, 
      # which is useful and required to use Prism plugins, but may be dangerous 
      # if the content isn't trustworthy.
      unsafe = true

[imaging]
  # JPEG and WebP image processing quality, defaults to 75%
  #quality = 75

[outputs]
  home = ["html", "rss", "searchIndex"]

[outputFormats]
  [outputFormats.searchIndex]
    mediaType = "application/json"
    baseName = "search-index"
    isPlainText = true
    notAlternative = true

[params]
  # dark or light, defaults to light. Local storage and OS preference override this param. For more details see: 
  # https://github.com/schnerring/hugo-theme-gruvbox/issues/34#issuecomment-1235870375
  defaultTheme = "dark"
  # gray red green yellow blue purple aqua orange, defaults to blue
  themeColor = "aqua"
  # soft medium hard, defaults to medium
  #themeContrast = "medium"
  author = "Yasin Karaaslan"

  [params.logo]
    #text = "yasin"
    url = "/"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "diff",
      "toml"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]
  
  # By default, the theme creates resized versions of images ranging from 300 to
  # 700 pixels wide in increments of 200 pixels
  #[params.imageResize]
  #  min = 300
  #  max = 700
  #  increment = 200
  
  [params.tagCloud]
    enable = false
    minFontSizeRem = 0.8
    maxFontSizeRem = 2.0

  # Social share links for posts:
  #   - iconSuite: "simple-icon" or "tabler-icon"
  #   - iconName: name of the icon from the "iconSuite"
  #   - {url} placeholder for post .Permalink
  #   - {title} placeholder for post .Title
  # See  https://github.com/bradvin/social-share-urls for more format strings
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "x"
    formatString = "https://x.com/intent/post?url={url}&text={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "linkedin"
    formatString = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "facebook"
    formatString = "https://www.facebook.com/sharer.php?u={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "reddit"
    formatString = "https://reddit.com/submit?url={url}&title={title}"
  [[params.socialShare]]
    iconSuite = "tabler-icon"
    iconName = "outline/mail"
    formatString = "mailto:?subject={title}&body={url}"

  [params.signIn]
    providers = [ 'x', 'google', 'github']
  

[languages]
  [languages.en]
    contentDir = 'content/en/'
    languageName = "English"
    languageCode = 'en-US'
    weight = 10

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts"
        weight = 10
      [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
          weight = 30
    [languages.en.params]
      mainSections = ['posts', 'short-stories']
      [languages.en.params.jsonResume]
        present = "present"


  [languages.tr]
    contentDir = 'content/tr/'
    disabled = false
    languageName = "Türkçe"
    languageCode = 'tr-TR'
    weight = 20


    [languages.tr.menu]
      [[languages.tr.menu.main]]
        identifier = "yazilar"
        name = "Yazılar"
        url = "/tr/yazilar"
        weight = 10
      [[languages.tr.menu.main]]
          identifier = "hakkimda"
          name = "Hakkımda"
          url = "/tr/hakkimda"
          weight = 30
          
    [languages.tr.params]
      mainSections = ['yazilar', 'kisa-hikayeler']
      [languages.tr.params.jsonResume]
        present = "şu an"
